rateLimits:
  /api/scan/v0/acs:
    name: acs
    type: limited
    maxTokens: 500         # The per-endpoint global limit (shared between all ips)
    tokensPerFill: 500
    fillInterval: 60s
    perIpRangeLimit: # per-IP-range limit
      maxTokens: 10
      tokensPerFill: 5
      fillInterval: 60s
