# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM python:3.12-slim@sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a

LABEL org.opencontainers.image.base.name="python:3.12-slim"

COPY restart-watchdog.py /restart-watchdog.py

COPY target/LICENSE .

# Ensure logs get output unbuffered even when the output is a pipe and don't write byte code in the container.
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

CMD ["python3", "/restart-watchdog.py"]
