name: Remind to backport PRs to release branches
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - cluster/deployment/**
      - cluster/configs/**
      - '**/expected.json'

jobs:
  add-backport-reminder:
    runs-on: ubuntu-24.04
    steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          with:
            submodules: 'true'
            token: ${{ secrets.GITHUB_TOKEN }}
        - uses: ./gha-scripts/actions/backport_reminder
          with:
            pr_number: ${{ github.event.pull_request.number }}
            lookup_prod_cluster_configs: false
            token: ${{ secrets.GH_CREATE_PRS_TOKEN }}
